FROM nvidia/cuda:12.9.0-cudnn-devel-ubuntu24.04

WORKDIR /app

RUN apt-get update

RUN apt-get install -y \
  python3-pip \
  python3-dev \
  libgl1-mesa-glx

RUN rm -rf /var/lib/apt/lists/*

COPY requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /Breast-Cancer-Classification

CMD ["python3", "Code1.py"]


