FROM pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime

COPY requirements.txt /tmp/requirements.txt
RUN pip install --nocache-dir -r /tmp/requirements.txt

COPY download_dataset.py /tmp/download_dataset.py
RUN mkdir -p /home/data3/Ali/Code/Saina/Brea/Dataset/
RUN python3 /tmp/download_dataset.py

COPY . /Breast-Cancer-Classification

WORKDIR /Breast-Cancer-Classification

RUN rm -rf /tmp/*